In [1]:
import numpy as np

## Practice

1. Create a 10*10 ndarray object, and the matrix boundary value is 1, and the rest are 0.


In [2]:
#1
m1 = np.zeros((10, 10))
for i in range(10):
    for j in range(10):
        if i * j == 0 or i == 9 or j == 9:
            m1[i, j] = 1
m1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

2. Create a 5*5 matrix with each row being 0 to 4

In [3]:
#2
m2 = np.stack([np.arange(0, 5) for _ in range(5)], axis=0)
m2

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

3. Create an 8*8 matrix and fill it with a checkerboard pattern, like [[0,1],[1,0]])

In [4]:
#3
m31 = np.where(np.arange(0, 7) % 2 == 1, 1.0, 0.0)
m32 = np.where(np.arange(0, 7) % 2 == 0, 1.0, 0.0)
m3 = np.vstack([m31, m32])
for _ in range(2):
    m3 = np.vstack([m3, m3])
m3

array([[0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1.]])

4. output all the odd numbers in the array  
   Example:  
   in:    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])  
   out:   array([1, 3, 5, 7, 9])  

In [5]:
#4
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
ans = []
for i in arr.flat:
    if i % 2 == 1:
        ans.append(i)
m4 = np.array(ans)
m4

array([1, 3, 5, 7, 9])

5. Normalize a 5x5 random matrix 

In [6]:
#5
def process5(matrix):
    sigma = np.std(matrix)
    miu = np.mean(matrix)
    return np.array([(x - miu) / sigma for x in matrix])


m5 = np.random.randn(5, 5)
process5(m5)

array([[-0.27704819, -1.06393494,  1.66194462, -0.01233254, -0.45932176],
       [-0.96215582, -0.60434406,  1.94622648, -0.44750417, -1.21673881],
       [ 1.35255236, -1.76917544,  1.85204254, -0.43333202, -0.19746696],
       [-0.46659388,  0.95448114,  0.88355346,  0.69098759,  0.32239037],
       [ 0.97413919, -0.94094838, -0.61475841, -0.42545357, -0.74720879]])

6. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates.

In [7]:
#6
import cmath


def process6(xs, ys):
    rs = []
    ts = []
    for i in range(len(xs)):
        cn = complex(xs[i], ys[i])
        r, t = cmath.polar(cn)
        rs.append(r)
        ts.append(t)
    return np.array(rs), np.array(ts)


xs = np.random.randn(5)
ys = np.random.randn(5)
process6(xs, ys)

(array([2.1521433 , 0.69066163, 1.57827536, 0.79941848, 1.23820613]),
 array([-2.28322481, -3.13543294,  1.87255919, -0.04582857,  1.62712218]))

7. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [8]:
#7
m70 = np.array([1, 2, 3, 4, 5])
ans = []
for i in range(len(m70) - 1):
    ans.append(m70[i])
    ans += [0 for _ in range(3)]
ans.append(m70[-1])
np.array(ans)

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

8. What are the result of the following expressions?

0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

np.nan in set([np.nan])

0.3 == 3 * 0.1 

(hint1:nan means not a number 
hint2:0.1(10) == 0.0001100110011001100110011001100110011001100110011...(2))
First guess a result, then print the result, and finally find why

In [9]:
#8
# 0 * np.nan
# np.nan == np.nan
# np.inf > np.nan
# np.nan - np.nan
# np.nan in set([np.nan])
0.3 == 3 * 0.1

False

9. What are the result of the following expressions? (Hint: the type of pn.nan is float)

np.array(0) / np.array(0)

np.array(0) // np.array(0)

np.array([np.nan]).astype(int).astype(float)


First guess a result, then print the result, and finally find why 

In [10]:
#9
# np.array(0) / np.array(0)
# np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])